name: flutter_gen_ai_chat_ui
description: A Flutter package that provides a customizable chat UI for AI applications, featuring streaming responses, code highlighting, and markdown support.
version: 1.1.9
homepage: https://github.com/hooshyar/flutter_gen_ai_chat_ui
repository: https://github.com/hooshyar/flutter_gen_ai_chat_ui
issue_tracker: https://github.com/hooshyar/flutter_gen_ai_chat_ui/issues
documentation: https://github.com/hooshyar/flutter_gen_ai_chat_ui/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dash_chat_2: ^0.0.21
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.6 
  url_launcher: ^6.3.1
  intl: ^0.19.0
  permission_handler: ^11.3.0
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
