name: flutter_gen_ai_chat_ui
description: A customizable chat UI package for Flutter applications, designed for AI chat interfaces.
version: 1.1.1
homepage: https://dilacode.com
repository: https://github.com/hooshyar/flutter_gen_ai_chat_ui
issue_tracker: https://github.com/hooshyar/flutter_gen_ai_chat_ui/issues
documentation: https://github.com/hooshyar/flutter_gen_ai_chat_ui#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  dash_chat_2: ^0.0.15
  shimmer: ^2.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
